version: '3'

services:
  web:
    build: ./DesafioBRMed
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./DesafioBRMed/:/usr/src/app/
    environment:
      - POSTGRES_USER=joandavi
      - POSTGRES_PASSWORD=super_password
      - POSTGRES_DB=desafio_br_med
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=joandavi
      - POSTGRES_PASSWORD=super_password
      - POSTGRES_DB=desafio_br_med
  ng:
    container_name: ng
    build: DesafioBRMed-app
    ports:
      - "8080:80"

volumes:
  postgres_data:
