# Generated by Django 4.0.1 on 2022-01-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brl', models.DecimalField(decimal_places=10, max_digits=17)),
                ('eur', models.DecimalField(decimal_places=10, max_digits=17)),
                ('jpy', models.DecimalField(decimal_places=10, max_digits=17)),
                ('date', models.DateField()),
            ],
        ),
    ]
